apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: docker-test
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: docker-test
        service: webapp
    spec:
      containers:
        - name: webapp
          image: nvdsfpoc.azurecr.io/sudarshan-jhawar/productapi:13
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: WebApiBaseAddress
              value: http://webapi
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: docker-test
    service: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: webapp
