apiVersion: apps/v1
   
kind: Deployment
   
metadata:
   
  labels:
   
    app.kubernetes.io/name: load-balancer-example
   
  name: product-api
   
spec:
   
  replicas: 5
   
  selector:
   
    matchLabels:
   
      app.kubernetes.io/name: load-balancer-example
   
  template:
   
    metadata:
   
      labels:
   
        app.kubernetes.io/name: load-balancer-example
   
    spec:
   
      containers:
   
      - image: nvdsfpoc.azurecr.io/sudarshan-jhawar/productapi:32
   
        name: product-api
   
        ports:
   
        - containerPort: 8080
   
