apiVersion: apps/v1
   
kind: Deployment
   
metadata:
   
  labels:
   
    app.kubernetes.io/name: nvdsfpoc.azurecr.io-productapi
   
  name: productapi
   
spec:
   
  replicas: 1
   
  selector:
   
    matchLabels:
   
      app.kubernetes.io/name: nvdsfpoc.azurecr.io-productapi
   
  template:
   
    metadata:
   
      labels:
   
        app.kubernetes.io/name: nvdsfpoc.azurecr.io-productapi
   
    spec:
   
      containers:
   
      - image: nvdsfpoc.azurecr.io/sudarshan-jhawar/productapi:32
   
        name: productapi
   
        ports:
   
        - containerPort: 8080
   
