apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  labels:
    app: docker-test
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapi
  template:
    metadata:
      labels:
        app: docker-test
        service: webapi
    spec:
      containers:
        - name: webapi
          image: nvdsfpoc.azurecr.io/sudarshan-jhawar/productapi:18
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
              targetPort: 9376
              type: LoadBalancer
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80

---
apiVersion: v1
kind: Service
metadata:
  name: webapi
  labels:
    app: docker-test
    service: webapi
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: webapi
